name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # let the action push to gh-pages
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # pull in any theme submodules
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.127.0'
          extended: true
      - name: Build
        run: hugo --minify --baseURL "https://<username>.github.io/<repo>/"
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
